# Generated by Django 6.0.3 on 2026-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="branch",
            field=models.CharField(
                choices=[
                    ("engineering", "Engineering"),
                    ("commerce", "Commerce"),
                    ("architecture", "Architecture"),
                ],
                max_length=50,
            ),
        ),
    ]
